### ISSUE TITLE
Build fails with cython 3.2.0

### ISSUE THREAD

**Issue by 0-wiz-0** [marcelm/cutadapt#864]
After updating cython in pkgsrc to 3.2.0, the build of cutadapt started failing. The pkgsrc version is 4.7, but the same error happens with the latest pypi version 5.2:
```
* Building wheel...
running bdist_wheel
running build
running build_py
creating build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/__init__.py -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/__main__.py -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/_match_tables.py -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/_version.py -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/adapters.py -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/align.py -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/cli.py -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/files.py -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/json.py -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/kmer_heuristic.py -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/log.py -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/modifiers.py -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/parser.py -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/pipeline.py -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/predicates.py -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/report.py -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/runners.py -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/statistics.py -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/steps.py -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/tokenizer.py -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/utils.py -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
running egg_info
writing src/cutadapt.egg-info/PKG-INFO
writing dependency_links to src/cutadapt.egg-info/dependency_links.txt
writing entry points to src/cutadapt.egg-info/entry_points.txt
writing requirements to src/cutadapt.egg-info/requires.txt
writing top-level names to src/cutadapt.egg-info/top_level.txt
reading manifest file 'src/cutadapt.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'src/cutadapt/*.c'
adding license file 'LICENSE'
writing manifest file 'src/cutadapt.egg-info/SOURCES.txt'
copying src/cutadapt/_align.pyi -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/_kmer_finder.pyi -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/info.pyi -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
copying src/cutadapt/qualtrim.pyi -> build/lib.netbsd-11.99.3-amd64-cpython-313/cutadapt
running build_ext
Compiling src/cutadapt/_align.pyx because it changed.
[1/1] Cythonizing src/cutadapt/_align.pyx
building 'cutadapt._align' extension
creating build/temp.netbsd-11.99.3-amd64-cpython-313/src/cutadapt
gcc -O2 -g -fstack-clash-protection -I/usr/include -I/usr/pkg/include/python3.13 -g -I/usr/include -I/usr/pkg/include/python3.13 -fPIC -I/usr/pkg/include/python3.13 -c src/cutadapt/_align.c -o build/temp.netbsd-11.99.3-a
md64-cpython-313/src/cutadapt/_align.o
src/cutadapt/_align.c: In function '__pyx_gb_8cutadapt_6_align_2generator':
src/cutadapt/_align.c:9097:36: error: assignment to expression with array type
 9097 |         __pyx_cur_scope->__pyx_t_4 = __pyx_t_9;
      |                                    ^
src/cutadapt/_align.c:9111:19: error: assignment to expression with array type
 9111 |         __pyx_t_9 = __pyx_cur_scope->__pyx_t_4;
      |                   ^
src/cutadapt/_align.c:9201:40: error: assignment to expression with array type
 9201 |             __pyx_cur_scope->__pyx_t_4 = __pyx_t_12;
      |                                        ^
src/cutadapt/_align.c:9206:41: error: assignment to expression with array type
 9206 |             __pyx_cur_scope->__pyx_t_11 = __pyx_t_17;
      |                                         ^
src/cutadapt/_align.c:9222:24: error: assignment to expression with array type
 9222 |             __pyx_t_12 = __pyx_cur_scope->__pyx_t_4;
      |                        ^
src/cutadapt/_align.c:9227:24: error: assignment to expression with array type
 9227 |             __pyx_t_17 = __pyx_cur_scope->__pyx_t_11;
      |                        ^
src/cutadapt/_align.c:9393:36: error: assignment to expression with array type
 9393 |         __pyx_cur_scope->__pyx_t_4 = __pyx_t_21;
      |                                    ^
src/cutadapt/_align.c:9411:20: error: assignment to expression with array type
 9411 |         __pyx_t_21 = __pyx_cur_scope->__pyx_t_4;
      |                    ^
```
I tried with with both Python 3.13 and 3.14.
If you think this is a bug in cython, please let me know and I'll file the bug report there. Thanks!

**Comment by pettyalex** [comment]
This also broke me today, so I hit it with a git bisect to see what's going on. This build failure first appears in 11c7fc90f298010caafe2172b64f6c8fa279af27, and v4.3 is the newest released version that builds successfully right now.

**Comment by marcelm** [comment]
I’m happy to report that the bug has been fixed in Cython 3.2.2, which was just released. Building Cutadapt should now work again.
